FROM node:22-alpine

ARG API_URL

ENV API_URL=${API_URL}

RUN apk update && apk upgrade

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm i

EXPOSE 3000

COPY  ./ ./

CMD ["npm", "run", "dev"]